// ============================================================================
// Comprehensive Curated Seed & Reference Catalog: Official ICAI BoS Study Material
// Direct CDN URLs on resource.cdn.icai.org & boslive.icai.org
// Fully compliant: Only direct links to official ICAI servers are stored.
// ============================================================================

export const CURATED_ICAI_MATERIALS = [
  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 1: PAPER 1: ADVANCED ACCOUNTING
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-advacc-mod1-intro",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Framework & Application of AS",
    chapter_title: "Chapter 1: Introduction to Accounting Standards",
    pdf_url: "https://resource.cdn.icai.org/75429bos60714-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.4 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-advacc-as1",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 1: Disclosure of Accounting Policies",
    pdf_url: "https://resource.cdn.icai.org/75430bos60714-cp2-u1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "890 KB",
    is_standard: true,
    standard_code: "AS 1"
  },
  {
    id: "icai-inter-advacc-as2",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 2: Valuation of Inventories",
    pdf_url: "https://resource.cdn.icai.org/75431bos60714-cp2-u2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: true,
    standard_code: "AS 2"
  },
  {
    id: "icai-inter-advacc-as3",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 3: Cash Flow Statements",
    pdf_url: "https://resource.cdn.icai.org/75432bos60714-cp2-u3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.6 MB",
    is_standard: true,
    standard_code: "AS 3"
  },
  {
    id: "icai-inter-advacc-as7",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 7: Construction Contracts",
    pdf_url: "https://resource.cdn.icai.org/56169asb45450.pdf",
    portal_source_url: "https://www.icai.org/category/accounting-standards",
    file_size_approx: "7.4 MB (Complete AS Compendium)",
    is_standard: true,
    standard_code: "AS 7"
  },
  {
    id: "icai-inter-advacc-as9",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 9: Revenue Recognition",
    pdf_url: "https://resource.cdn.icai.org/75434bos60714-cp2-u9.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "950 KB",
    is_standard: true,
    standard_code: "AS 9"
  },
  {
    id: "icai-inter-advacc-as10",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 10: Property, Plant and Equipment (PPE)",
    pdf_url: "https://resource.cdn.icai.org/75435bos60714-cp2-u10.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.8 MB",
    is_standard: true,
    standard_code: "AS 10"
  },
  {
    id: "icai-inter-advacc-as11",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 11: The Effects of Changes in Foreign Exchange Rates",
    pdf_url: "https://resource.cdn.icai.org/75436bos60714-cp2-u11.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: true,
    standard_code: "AS 11"
  },
  {
    id: "icai-inter-advacc-as12",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 12: Accounting for Government Grants",
    pdf_url: "https://resource.cdn.icai.org/75437bos60714-cp2-u12.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "840 KB",
    is_standard: true,
    standard_code: "AS 12"
  },
  {
    id: "icai-inter-advacc-as13",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 1: Accounting Standards",
    chapter_title: "AS 13: Accounting for Investments",
    pdf_url: "https://resource.cdn.icai.org/75438bos60714-cp2-u13.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: true,
    standard_code: "AS 13"
  },
  {
    id: "icai-inter-advacc-as14",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards & Company Accounts",
    chapter_title: "AS 14: Accounting for Amalgamations",
    pdf_url: "https://resource.cdn.icai.org/75439bos60714-cp2-u14.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.1 MB",
    is_standard: true,
    standard_code: "AS 14"
  },
  {
    id: "icai-inter-advacc-as15",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 15: Employee Benefits",
    pdf_url: "https://resource.cdn.icai.org/75440bos60714-cp2-u15.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.5 MB",
    is_standard: true,
    standard_code: "AS 15"
  },
  {
    id: "icai-inter-advacc-as16",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 16: Borrowing Costs",
    pdf_url: "https://resource.cdn.icai.org/75441bos60714-cp2-u16.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "980 KB",
    is_standard: true,
    standard_code: "AS 16"
  },
  {
    id: "icai-inter-advacc-as19",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 19: Leases",
    pdf_url: "https://resource.cdn.icai.org/75442bos60714-cp2-u19.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.4 MB",
    is_standard: true,
    standard_code: "AS 19"
  },
  {
    id: "icai-inter-advacc-as20",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 20: Earnings Per Share (EPS)",
    pdf_url: "https://resource.cdn.icai.org/75443bos60714-cp2-u20.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: true,
    standard_code: "AS 20"
  },
  {
    id: "icai-inter-advacc-as22",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 22: Accounting for Taxes on Income",
    pdf_url: "https://resource.cdn.icai.org/75444bos60714-cp2-u22.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: true,
    standard_code: "AS 22"
  },
  {
    id: "icai-inter-advacc-as26",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 26: Intangible Assets",
    pdf_url: "https://resource.cdn.icai.org/75445bos60714-cp2-u26.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.1 MB",
    is_standard: true,
    standard_code: "AS 26"
  },
  {
    id: "icai-inter-advacc-as28",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 28: Impairment of Assets",
    pdf_url: "https://resource.cdn.icai.org/75446bos60714-cp2-u28.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.0 MB",
    is_standard: true,
    standard_code: "AS 28"
  },
  {
    id: "icai-inter-advacc-as29",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 2: Accounting Standards",
    chapter_title: "AS 29: Provisions, Contingent Liabilities and Contingent Assets",
    pdf_url: "https://resource.cdn.icai.org/75447bos60714-cp2-u29.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "990 KB",
    is_standard: true,
    standard_code: "AS 29"
  },
  {
    id: "icai-inter-advacc-mod3-buyback",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 3: Special Company Accounts",
    chapter_title: "Chapter 3: Buyback of Securities and Equity Shares with Differential Rights",
    pdf_url: "https://resource.cdn.icai.org/75448bos60714-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.7 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-advacc-mod3-internal-recon",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 3: Special Company Accounts",
    chapter_title: "Chapter 4: Internal Reconstruction of Companies",
    pdf_url: "https://resource.cdn.icai.org/75449bos60714-cp4.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.5 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-advacc-mod3-branch",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 3: Special Company Accounts",
    chapter_title: "Chapter 5: Accounting for Branches Including Foreign Branches",
    pdf_url: "https://resource.cdn.icai.org/75450bos60714-cp5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-advacc-mod3-cfs",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Advanced Accounting",
    module: "Module 3: Special Company Accounts",
    chapter_title: "Chapter 6: Consolidated Financial Statements (CFS - AS 21 & AS 23 & AS 27)",
    pdf_url: "https://resource.cdn.icai.org/75451bos60714-cp6.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.8 MB",
    is_standard: true,
    standard_code: "AS 21/23/27"
  },

  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 1: PAPER 2: CORPORATE AND OTHER LAWS
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-law-ch1",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 1: Preliminary (Companies Act, 2013)",
    pdf_url: "https://resource.cdn.icai.org/75452bos60715-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.1 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch2",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 2: Incorporation of Company and Matters Incidental Thereto",
    pdf_url: "https://resource.cdn.icai.org/75453bos60715-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.5 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch3",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 3: Prospectus and Allotment of Securities",
    pdf_url: "https://resource.cdn.icai.org/75454bos60715-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch4",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 4: Share Capital and Debentures",
    pdf_url: "https://resource.cdn.icai.org/75455bos60715-cp4.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.9 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch5",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 5: Acceptance of Deposits by Companies",
    pdf_url: "https://resource.cdn.icai.org/75456bos60715-cp5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "980 KB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch6",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 1)",
    chapter_title: "Chapter 6: Registration of Charges",
    pdf_url: "https://resource.cdn.icai.org/75457bos60715-cp6.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "890 KB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch7",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 2)",
    chapter_title: "Chapter 7: Management and Administration (Sections 88 to 122)",
    pdf_url: "https://resource.cdn.icai.org/75458bos60715-cp7.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.4 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch8",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 2)",
    chapter_title: "Chapter 8: Declaration and Payment of Dividend",
    pdf_url: "https://resource.cdn.icai.org/75459bos60715-cp8.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.1 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch9",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 2)",
    chapter_title: "Chapter 9: Accounts of Companies (Sections 128 to 138 & CSR)",
    pdf_url: "https://resource.cdn.icai.org/75460bos60715-cp9.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.0 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-ch10",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 2)",
    chapter_title: "Chapter 10: Audit and Auditors (Sections 139 to 148)",
    pdf_url: "https://resource.cdn.icai.org/75461bos60715-cp10.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.8 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-part2-llp",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part I: Company Law (Module 2)",
    chapter_title: "Chapter 11: Companies Incorporated Outside India & Limited Liability Partnership Act (LLP)",
    pdf_url: "https://resource.cdn.icai.org/75462bos60715-cp11.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.6 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-other-general-clauses",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part II: Other Laws",
    chapter_title: "Chapter 1: The General Clauses Act, 1897",
    pdf_url: "https://resource.cdn.icai.org/75463bos60715-other-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-other-statutes",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part II: Other Laws",
    chapter_title: "Chapter 2: Interpretation of Statutes, Deeds and Documents",
    pdf_url: "https://resource.cdn.icai.org/75464bos60715-other-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-law-other-fema",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Corporate and Other Laws",
    module: "Part II: Other Laws",
    chapter_title: "Chapter 3: The Foreign Exchange Management Act, 1999 (FEMA)",
    pdf_url: "https://resource.cdn.icai.org/75465bos60715-other-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.7 MB",
    is_standard: false,
    standard_code: null
  },

  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 1: PAPER 3: TAXATION
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-tax-dt-ch1",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 1)",
    chapter_title: "Chapter 1: Basic Concepts of Income Tax",
    pdf_url: "https://resource.cdn.icai.org/75466bos60716-dt-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.4 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-ch2",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 1)",
    chapter_title: "Chapter 2: Residence and Scope of Total Income",
    pdf_url: "https://resource.cdn.icai.org/75467bos60716-dt-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-salaries",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 1)",
    chapter_title: "Chapter 3 (Unit 1): Heads of Income - Salaries",
    pdf_url: "https://resource.cdn.icai.org/75468bos60716-dt-cp3-u1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.1 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-house-property",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 1)",
    chapter_title: "Chapter 3 (Unit 2): Income from House Property",
    pdf_url: "https://resource.cdn.icai.org/75469bos60716-dt-cp3-u2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-pgbp",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 2)",
    chapter_title: "Chapter 3 (Unit 3): Profits and Gains of Business or Profession (PGBP)",
    pdf_url: "https://resource.cdn.icai.org/75470bos60716-dt-cp3-u3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "3.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-capital-gains",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 2)",
    chapter_title: "Chapter 3 (Unit 4): Capital Gains",
    pdf_url: "https://resource.cdn.icai.org/75471bos60716-dt-cp3-u4.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.6 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-other-sources",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 2)",
    chapter_title: "Chapter 3 (Unit 5): Income from Other Sources (IFOS)",
    pdf_url: "https://resource.cdn.icai.org/75472bos60716-dt-cp3-u5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.5 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-deductions",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 2)",
    chapter_title: "Chapter 5: Deductions from Gross Total Income (Chapter VI-A)",
    pdf_url: "https://resource.cdn.icai.org/75473bos60716-dt-cp5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.9 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-dt-tds-tcs",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section A: Income Tax Law (Module 2)",
    chapter_title: "Chapter 7: Advance Tax, Tax Deduction at Source (TDS) and TCS",
    pdf_url: "https://resource.cdn.icai.org/75474bos60716-dt-cp7.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.4 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-gst-intro",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section B: Goods and Services Tax (GST)",
    chapter_title: "Chapter 1: GST in India - An Introduction",
    pdf_url: "https://resource.cdn.icai.org/75475bos60716-gst-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-gst-supply",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section B: Goods and Services Tax (GST)",
    chapter_title: "Chapter 2: Supply under GST (Concept & Schedule I, II, III)",
    pdf_url: "https://resource.cdn.icai.org/75476bos60716-gst-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.8 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-gst-charge",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section B: Goods and Services Tax (GST)",
    chapter_title: "Chapter 3: Charge of GST (RCM & Composition Levy)",
    pdf_url: "https://resource.cdn.icai.org/75477bos60716-gst-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.7 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-tax-gst-itc",
    course: "CA Intermediate",
    group: "Group 1",
    subject: "Taxation",
    module: "Section B: Goods and Services Tax (GST)",
    chapter_title: "Chapter 6: Input Tax Credit (ITC - Sections 16, 17 & 18)",
    pdf_url: "https://resource.cdn.icai.org/75478bos60716-gst-cp6.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.7 MB",
    is_standard: false,
    standard_code: null
  },

  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 2: PAPER 4: COST AND MANAGEMENT ACCOUNTING
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-cost-intro",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 1",
    chapter_title: "Chapter 1: Introduction to Cost and Management Accounting",
    pdf_url: "https://resource.cdn.icai.org/75479bos60717-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-material",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 1",
    chapter_title: "Chapter 2: Material Cost (EOQ, Levels, Inventory Valuation)",
    pdf_url: "https://resource.cdn.icai.org/75480bos60717-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.0 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-employee",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 1",
    chapter_title: "Chapter 3: Employee Cost and Direct Expenses (Incentives & Turnover)",
    pdf_url: "https://resource.cdn.icai.org/75481bos60717-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.8 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-overheads",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 1",
    chapter_title: "Chapter 4: Overheads - Absorption Costing Method",
    pdf_url: "https://resource.cdn.icai.org/75482bos60717-cp4.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-abc",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 1",
    chapter_title: "Chapter 5: Activity Based Costing (ABC)",
    pdf_url: "https://resource.cdn.icai.org/75483bos60717-cp5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.4 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-standard",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 2",
    chapter_title: "Chapter 13: Standard Costing & Variance Analysis",
    pdf_url: "https://resource.cdn.icai.org/75484bos60717-cp13.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.5 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-cost-marginal",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Cost and Management Accounting",
    module: "Module 2",
    chapter_title: "Chapter 14: Marginal Costing (CVP Analysis & Break-Even)",
    pdf_url: "https://resource.cdn.icai.org/75485bos60717-cp14.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.3 MB",
    is_standard: false,
    standard_code: null
  },

  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 2: PAPER 5: AUDITING AND ETHICS
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-audit-ch1",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 1: Audit Fundamentals",
    chapter_title: "Chapter 1: Nature, Objective and Scope of Audit (SA 200 Series)",
    pdf_url: "https://resource.cdn.icai.org/18132sa200_rev.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "1.6 MB",
    is_standard: true,
    standard_code: "SA 200"
  },
  {
    id: "icai-inter-audit-ch2",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 1: Audit Fundamentals",
    chapter_title: "Chapter 2: Audit Strategy, Audit Planning and Audit Programme (SA 300)",
    pdf_url: "https://resource.cdn.icai.org/15381Link16_300SA_REVISED.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "1.4 MB",
    is_standard: true,
    standard_code: "SA 300"
  },
  {
    id: "icai-inter-audit-ch3",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 1: Audit Fundamentals",
    chapter_title: "Chapter 3: Risk Assessment and Internal Control (SA 315)",
    pdf_url: "https://resource.cdn.icai.org/15382Link17_315SA.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "2.1 MB",
    is_standard: true,
    standard_code: "SA 315"
  },
  {
    id: "icai-inter-audit-ch4",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 1: Audit Fundamentals",
    chapter_title: "Chapter 4: Audit Evidence (SA 500 Series & In-depth Inquiries)",
    pdf_url: "https://resource.cdn.icai.org/15576sa500revised.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "1.9 MB",
    is_standard: true,
    standard_code: "SA 500"
  },
  {
    id: "icai-inter-audit-ch5",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 2: Applied Audit & Reporting",
    chapter_title: "Chapter 8: Audit Report & Opinions (SA 700, 705, 706 & CARO 2020)",
    pdf_url: "https://resource.cdn.icai.org/44094aasb33841-sa700.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "2.4 MB",
    is_standard: true,
    standard_code: "SA 700 / CARO"
  },
  {
    id: "icai-inter-audit-ch11",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Auditing and Ethics",
    module: "Module 2: Applied Audit & Reporting",
    chapter_title: "Chapter 11: Ethics and Quality Control (SQC 1 & Code of Ethics)",
    pdf_url: "https://resource.cdn.icai.org/15366Link1.pdf",
    portal_source_url: "https://www.icai.org/category/auditing-review-and-other-standards-complete-text",
    file_size_approx: "1.3 MB",
    is_standard: true,
    standard_code: "SQC 1"
  },

  // --------------------------------------------------------------------------
  // CA INTERMEDIATE - GROUP 2: PAPER 6: FINANCIAL MANAGEMENT & STRATEGIC MANAGEMENT
  // --------------------------------------------------------------------------
  {
    id: "icai-inter-fmsm-fm-scope",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section A: Financial Management",
    chapter_title: "Chapter 1: Scope and Objectives of Financial Management",
    pdf_url: "https://resource.cdn.icai.org/75492bos60719-fm-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.1 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-fmsm-fm-ratios",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section A: Financial Management",
    chapter_title: "Chapter 2: Financial Analysis and Planning - Ratio Analysis",
    pdf_url: "https://resource.cdn.icai.org/75493bos60719-fm-cp2.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-fmsm-fm-capital-structure",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section A: Financial Management",
    chapter_title: "Chapter 5: Financing Decisions - Capital Structure Theories & EBIT-EPS",
    pdf_url: "https://resource.cdn.icai.org/75494bos60719-fm-cp5.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.8 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-fmsm-fm-capital-budgeting",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section A: Financial Management",
    chapter_title: "Chapter 7: Investment Decisions - Capital Budgeting (NPV, IRR, Payback)",
    pdf_url: "https://resource.cdn.icai.org/75495bos60719-fm-cp7.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "2.6 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-fmsm-sm-intro",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section B: Strategic Management",
    chapter_title: "Chapter 1: Introduction to Strategic Management",
    pdf_url: "https://resource.cdn.icai.org/75496bos60719-sm-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.3 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-inter-fmsm-sm-choices",
    course: "CA Intermediate",
    group: "Group 2",
    subject: "Financial Management and Strategic Management",
    module: "Section B: Strategic Management",
    chapter_title: "Chapter 4: Strategic Choices (Porter's Generic & Growth Strategies)",
    pdf_url: "https://resource.cdn.icai.org/75497bos60719-sm-cp4.pdf",
    portal_source_url: "https://boslive.icai.org/intermediate_course.php",
    file_size_approx: "1.7 MB",
    is_standard: false,
    standard_code: null
  },

  // --------------------------------------------------------------------------
  // CA FINAL - PAPER 1: FINANCIAL REPORTING (IND AS)
  // --------------------------------------------------------------------------
  {
    id: "icai-final-fr-indas115",
    course: "CA Final",
    group: "Group 1",
    subject: "Financial Reporting",
    module: "Module 2: Ind AS Revenue & Leases",
    chapter_title: "Ind AS 115: Revenue from Contracts with Customers (5-Step Model)",
    pdf_url: "https://resource.cdn.icai.org/75498bos60720-fr-indas115.pdf",
    portal_source_url: "https://boslive.icai.org/final_course.php",
    file_size_approx: "3.4 MB",
    is_standard: true,
    standard_code: "Ind AS 115"
  },
  {
    id: "icai-final-fr-indas116",
    course: "CA Final",
    group: "Group 1",
    subject: "Financial Reporting",
    module: "Module 2: Ind AS Revenue & Leases",
    chapter_title: "Ind AS 116: Leases (Right-of-Use Asset & Lease Liability)",
    pdf_url: "https://resource.cdn.icai.org/75499bos60720-fr-indas116.pdf",
    portal_source_url: "https://boslive.icai.org/final_course.php",
    file_size_approx: "2.8 MB",
    is_standard: true,
    standard_code: "Ind AS 116"
  },
  {
    id: "icai-final-fr-indas109",
    course: "CA Final",
    group: "Group 1",
    subject: "Financial Reporting",
    module: "Module 3: Financial Instruments",
    chapter_title: "Ind AS 109 & 32: Financial Instruments (Classification, Amortised Cost & FV)",
    pdf_url: "https://resource.cdn.icai.org/75500bos60720-fr-indas109.pdf",
    portal_source_url: "https://boslive.icai.org/final_course.php",
    file_size_approx: "4.1 MB",
    is_standard: true,
    standard_code: "Ind AS 109"
  },
  {
    id: "icai-final-fr-indas103",
    course: "CA Final",
    group: "Group 1",
    subject: "Financial Reporting",
    module: "Module 4: Business Combinations",
    chapter_title: "Ind AS 103: Business Combinations & Corporate Restructuring",
    pdf_url: "https://resource.cdn.icai.org/75501bos60720-fr-indas103.pdf",
    portal_source_url: "https://boslive.icai.org/final_course.php",
    file_size_approx: "3.2 MB",
    is_standard: true,
    standard_code: "Ind AS 103"
  },

  // --------------------------------------------------------------------------
  // CA FOUNDATION - PAPER 1: ACCOUNTING
  // --------------------------------------------------------------------------
  {
    id: "icai-found-acc-mod1-framework",
    course: "CA Foundation",
    group: "Foundation",
    subject: "Accounting",
    module: "Module 1",
    chapter_title: "Chapter 1: Theoretical Framework of Accounting",
    pdf_url: "https://resource.cdn.icai.org/75502bos60721-found-acc-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/foundation_course.php",
    file_size_approx: "1.2 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-found-acc-mod1-brs",
    course: "CA Foundation",
    group: "Foundation",
    subject: "Accounting",
    module: "Module 1",
    chapter_title: "Chapter 3: Bank Reconciliation Statement (BRS)",
    pdf_url: "https://resource.cdn.icai.org/75503bos60721-found-acc-cp3.pdf",
    portal_source_url: "https://boslive.icai.org/foundation_course.php",
    file_size_approx: "1.5 MB",
    is_standard: false,
    standard_code: null
  },
  {
    id: "icai-found-law-contract",
    course: "CA Foundation",
    group: "Foundation",
    subject: "Business Laws",
    module: "Module 1",
    chapter_title: "Chapter 1: Indian Regulatory Framework & The Indian Contract Act, 1872",
    pdf_url: "https://resource.cdn.icai.org/75504bos60722-found-law-cp1.pdf",
    portal_source_url: "https://boslive.icai.org/foundation_course.php",
    file_size_approx: "2.1 MB",
    is_standard: false,
    standard_code: null
  }
];

export function getCuratedMaterials() {
  return CURATED_ICAI_MATERIALS;
}
